### ISSUE TITLE
Is it possible to support Pocket Casts and Airr?

### ISSUE THREAD

**Issue by wenlzhang** [marcjulianschwarz/obsidian-podcast-note#1]
Is it possible to support the following podcast apps?

- [Pocket Casts: Listen to podcasts with the best free podcasting app - built by listeners, for listeners.](https://www.pocketcasts.com/)
- [Airr: Highlight moments from audio. Host async audio conversations.](https://www.airr.io/)

**Comment by marcjulianschwarz** [comment]
For now it only supports apple and Spotify but I just tried to implement:
- Pocket Casts
- Airr
- Overcast

I just need to test it first and will push it later today or tomorrow.

With the official release in "Obsidian community plugins", more podcast services will be supported.

**Comment by wenlzhang** [comment]
Thanks for the prompt response! Looking forward to that!

**Comment by marcjulianschwarz** [comment]
No problem.

Pocket Casts, Airr and Overcast are now working.
Do you know any other podcast services which should be added?

**Comment by marcjulianschwarz** [comment]
https://user-images.githubusercontent.com/67844154/132004132-4571d4c2-651a-4306-ab0e-57c128f9db88.mp4

**Comment by wenlzhang** [comment]
The following may be of interest:

- Google Podcast
- Castbox
- Castro
- AntennaPod
- Listen Notes
  - This is a search engine for podcasts, which may be interesting to add.

**Comment by marcjulianschwarz** [comment]
Thank you, will look into them.

**Comment by marcjulianschwarz** [comment]
Google Podcast, Castbox, Castro are working too.

AntennaPod only woks on Android. Since I don't have any android device, I can't test this one.

When I try to fetch podcast data from listen notes it will only respond with an empty html. I guess they don't want their data to be automatically fetched because they have the biggest podcast database which they get money for.

**Comment by marcjulianschwarz** [comment]
Podcast Note is now an official community plugin supporting all of these podcast services.

**Comment by wenlzhang** [comment]
Is it also possible to support Snipd and Momento?
https://www.snipd.com/
https://momento.fm/
