### ISSUE TITLE
Is it possible to support Snipd and Momento?

### ISSUE THREAD

**Issue by wenlzhang** [marcjulianschwarz/obsidian-podcast-note#10]
Since the issue https://github.com/marcjulianschwarz/obsidian-podcast-note/issues/1#issuecomment-916320486 has been closed, it might be better to have a new issue for this. 😃

Is it also possible to support Snipd and Momento?
https://www.snipd.com/
https://momento.fm/

**Comment by wenlzhang** [comment]
Similar to Airr, these are also podcast highlight apps. So it would be great if the following issue can also be integrated:
https://github.com/marcjulianschwarz/obsidian-podcast-note/issues/4

**Comment by marcjulianschwarz** [comment]
I can't get snipd to run properly on my devices. 
Will implement momento for the next release.

Will discuss the rest in #4

**Comment by marcjulianschwarz** [comment]
Looks like Snipd built their own export function for Obsidian:

https://blog.snipd.com/how-to-export-your-podcast-highlights-to-obsidian-54208c06d491
