### ISSUE TITLE
Support more customization in note template

### ISSUE THREAD

**Issue by wenlzhang** [marcjulianschwarz/obsidian-podcast-note#11]
It would be great if the following can be improved/supported when in the podcast note template:

- One can set something like `{{date:YYYY-MM-DD}}T{{time:HH:mm}}`, e.g. in the note content, or `{{date:YYYYMMDD}}{{time:HHmm}}`, e.g. in the note title.
  - Currently, `{{Date}}` and `{{Timestamp}}` would generate a different format.
- The release date/time of the podcast episode
- Podcast host and creator

If some of the information listed above cannot be found in one Podcast app/service, is it possible to automatically fetch those fields from other Podcast apps/services?

**Comment by marcjulianschwarz** [comment]
Moved to #13
