### ISSUE TITLE
Add Podcast Notes from Selection does not work for pure links

### ISSUE THREAD

**Issue by wenlzhang** [marcjulianschwarz/obsidian-podcast-note#12]
As can be seen from the GIF below, if the episode is a pure link, it cannot generate a podcast note from the selected URL. If the link is in the format of Markdown link, i.e. `[Text](Link)`, then the podcast note would be created correctly.
![CleanShot 2021-09-10 at 13 38 59](https://user-images.githubusercontent.com/44930227/132848242-4cf74048-a51c-4e6a-89b6-7832be33d9c4.gif)

**Comment by marcjulianschwarz** [comment]
This is now working. Will be in the next release.
