### ISSUE TITLE
Placeholder suggestions

### ISSUE THREAD

**Issue by marcjulianschwarz** [marcjulianschwarz/obsidian-podcast-note#13]
# Placeholder suggestions
Please add new placeholder suggestions in the comments, I will add them to the list.

- {{date:YYYY-MM-DD}}, {{time:HH:mm}}
- {{AiredDate}} — when the episode aired
- {{Station}} — the name of the podcast station/show/host/creator
- {{EpisodeNumber}} — if episodes are numbered for the given station
- {{RunTime}} — the duration of the episode (e.g., 1:23:45)
- {{Tags}} — any tags associated with the episode

**Comment by sirlaughalot90** [comment]
I'd love to see a placeholder for the complete show notes. I intend to use your plugin to save links that are mentioned in a show and find their way into the show notes. However, this is not possible at the moment. Would be great to see this added. Thank you!

**Comment by marcjulianschwarz** [comment]
Do you mean the notes discussed in #14 when you are talking about "show notes"?

**Comment by sirlaughalot90** [comment]
Yes, exactly. Another good example for a podcast which heavily relies on show notes would be ATP and many, many other indie podcasts: https://atp.fm/456. Overcast and Castro would be two players which support it very well.

**Comment by marcjulianschwarz** [comment]
Hi @cashew90,
worked on show notes for Castro and other podcast services. I couldn't find a link on overcast with show notes.
For more info and some examples see #14.

**Comment by marcjulianschwarz** [comment]
Closing as this information is only available for few podcast services and there is no clear way as to how to scrape that data.
