### ISSUE TITLE
Support for Podcast Notes

### ISSUE THREAD

**Issue by Ramanathan10** [marcjulianschwarz/obsidian-podcast-note#14]
Several podcasts have detailed show notes. It would be nice to have a placeholder for {{Notes}} that pulls in show notes.

**Comment by marcjulianschwarz** [comment]
Can you show me a podcast that has these show notes?

**Comment by Ramanathan10** [comment]
![A2F346F7-2849-4355-A2D6-1B171C8EA95D](https://user-images.githubusercontent.com/18464407/132962413-53bbf1ed-e694-46a6-9679-7a3dd8a81e66.jpeg)

**Comment by marcjulianschwarz** [comment]
Which service are you using? Could you share a link to that podcast?

**Comment by EvilOne** [comment]
Here is an example of another Podcast with notes: https://pca.st/episode/50a66260-a0c3-4f2e-be4c-118d4d6cafd9

**Comment by Ramanathan10** [comment]
> Which service are you using? Could you share a link to that podcast?

Show notes appear when using Overcast app or certain podcast players support a web version like @EvilOne has linked that has show notes

**Comment by IanPatterson99** [comment]
Can I second this request please? I use Pocket Casts, but the description gets cut very short. Here’s one example. https://pca.st/episode/a7a2a4ae-b061-4836-803a-47d0e7f542d6
In particular, all of the show links here are in the notes. Thanks - great plugin btw.

**Comment by marcjulianschwarz** [comment]
Hi @Ramanathan10 @EvilOne @IanPatterson99,
I found some time and started working on show notes for Pocket Casts.

This is the example @IanPatterson99 sent:
<img width="1151" alt="Bildschirmfoto 2021-12-05 um 17 35 56" src="https://user-images.githubusercontent.com/67844154/144755114-fef519fd-f843-4904-a7a3-e67eba2ee178.png">

This is the example @EvilOne sent:
<img width="1143" alt="Bildschirmfoto 2021-12-05 um 17 36 52" src="https://user-images.githubusercontent.com/67844154/144755142-6faf2b4b-6f7f-4a85-910a-8ed8a46b71e9.png">

Does this look good? You will be able to get this by using the `{{ShowNotes}}` placeholder.

**Comment by marcjulianschwarz** [comment]
> Show notes appear when using Overcast app or certain podcast players support a web version like @EvilOne has linked that has show notes

@Ramanathan10 
I don't see any show notes on the web version of overcast. Could you send me a link with show notes?

**Comment by marcjulianschwarz** [comment]
Show Notes for a podcast on Castro:
<img width="380" alt="Bildschirmfoto 2021-12-05 um 17 48 02" src="https://user-images.githubusercontent.com/67844154/144755589-8b780288-5c62-4056-b27a-331f149bd542.png">

**Comment by sirlaughalot90** [comment]
Looking good! When will you be able to push the update? 😇

**Comment by marcjulianschwarz** [comment]
Will try to get it pushed until tomorrow. I want to add some small fixes and maybe include #17 too.

**Comment by EvilOne** [comment]
Looks real good! Thanks for taking the time to do this.

**Comment by marcjulianschwarz** [comment]
@cashew90 and @EvilOne,
I just released the new version which you can update to now. However I have to say that since PocketCasts doesn't have an API, I had to use an unusual workaround to get this to work so this might be breaking when PocketCasts changes their source code for their web version.
Let me know when something doesn't work.
