### ISSUE TITLE
Another use case idea 

### ISSUE THREAD

**Issue by thecookiemomma** [marcjulianschwarz/obsidian-podcast-note#15]
Hello! 
I love this plugin because it meets a need I have to take notes on podcasts. I wonder, though if that could be expanded to YouTube videos?  I wouldn't expect embedding, just the link and maybe the thumbnail of the vid.  I consume more YouTube than I do podcasts, and this would be perfect for that.  If not, that's okay, but I thought I'd bring it up. Thanks again for all your hard work!

**Comment by marcjulianschwarz** [comment]
Do you listen to podcasts on YouTube?
If not, then this wouldn't fit with what the plugin was made for.

**Comment by thecookiemomma** [comment]
Yes. I listen to podcasts and podcast type formats on Youtube.

**Comment by DryIce1** [comment]
Hi @marcjulianschwarz, such a useful plugin, thanks!

> Do you listen to podcasts on YouTube? If not, then this wouldn't fit with what the plugin was made for.

I am curious about why you see a difference between podcasts and YouTube media? Is there a technical difference in how the plugin retrieves metadata? Is it more difficult to retrieve it from YouTube URL compared with a podcast URL?

For me, retrieving this type of metadata from the source podcasts and formatting it in an obsidian template is so useful, and it would be amazing to also be able to link my original ideas that have been inspired by YouTube videos too.

The way that you explain the Readme, it makes sense to me that it would be highly relevant for YouTube 
> Podcast Note is a great way to write notes on Podcasts [**and YouTube Videos**]. With a single URL you will get the Podcast[/**Youtube**] title, image and description of your podcast or YouTube video. Using a custom template you can style the note to your liking.

thanks again,
best

**Comment by marcjulianschwarz** [comment]
Thank you for the feedback. I see your point @DryIce1 and @thecookiemomma.

Here you go:
![youtube notes](https://user-images.githubusercontent.com/67844154/138589503-f83720b6-1bfc-436a-ab69-a03403f4620e.png)

Will upload this with a new release but I will have to test it first. And I am still struggling to get the whole description. Will let you both know when it is ready.
