### ISSUE TITLE
Some help with google podcasts

### ISSUE THREAD

**Issue by Keysz** [marcjulianschwarz/obsidian-podcast-note#16]
On a Mac OS - trying to load an example podcast from google podcasts into the podcast note, but I keep getting an error 'Couldn't load podcast - no internet connection'. I do have internet connection but still experiencing this error. 

This is an example url, but none of them seem to work for me. 
https://podcasts.google.com/feed/aHR0cHM6Ly93d3cub21ueWNvbnRlbnQuY29tL2QvcGxheWxpc3QvZDgzZjUyZTQtMjQ1NS00N2Y0LTk4MmUtYWI3OTAxMjBiOTU0LzZiZTVhMDFiLWNjYTQtNDg1Yi1hNDAyLWFiODYwMGQzZWVjMy82MjE4YmQ1Yy05NTk4LTQ3YjUtOGQ5My1hYjg2MDBkM2VlYzMvcG9kY2FzdC5yc3M/episode/YjA1ZDUyMjktMDJmMy00ODA2LWJjYmUtYWQ5ZjAxM2IxY2Ji?sa=X&ved=0CAcQkfYCahgKEwjIwI6Xjv3yAhUAAAAAHQAAAAAQ-QE

**Comment by marcjulianschwarz** [comment]
I tried it with the link you provided and it worked for me (on macOS).

![](https://user-images.githubusercontent.com/67844154/133206245-13d8a534-f37f-41b1-8e58-d31e762ae170.png)

Can you tell me which version of Podcast Note you have installed?

**Comment by Keysz** [comment]
Version 1.1.2 - Not sure what the issue. It still doesn't work for me. Add a podcast note -> entered the url -> keeps giving me the error 'couldn't load podcast data.

**Comment by marcjulianschwarz** [comment]
Sorry for the delayed response. Are you using the plugin on a windows device?
