### ISSUE TITLE
Choose specific markdown file as the Template for Podcast Note 

### ISSUE THREAD

**Issue by DryIce1** [marcjulianschwarz/obsidian-podcast-note#17]
Hi, if possible, it would be great to be able to select the specific file which Podcast Note uses 

**Current solution** 
- the user writes their template in the Podcast Note settings pane
![image](https://user-images.githubusercontent.com/59501376/144707809-e73baec8-fb29-42c1-9a2a-fb8bf578978a.png)

**Proposed solution**
- the user selects the specific file (e.g. The Daily Note or Periodic Notes plugins do this)
- ![image](https://user-images.githubusercontent.com/59501376/144707946-b1e97cee-7a39-49df-a864-750acd5654e3.png)

**Reason**
- it is easier to edit the template if it is a file rather than through the settings

**Comment by marcjulianschwarz** [comment]
Hi @DryIce1,
thank you for the feature request. That's a good idea, will let you know when it's implemented.

**Comment by marcjulianschwarz** [comment]
This is now an available option in version 1.3.0 

Thank you!
