### ISSUE TITLE
Update {{ImageURL}} for Pocketcasts streams to retrieve "https://" links (currently retrieving http://)

### ISSUE THREAD

**Issue by DryIce1** [marcjulianschwarz/obsidian-podcast-note#18]
Guten abend @marcjulianschwarz,

**Problem**

- With Pocketcast imports, the {{ImageURL}} placeholder is currently retrieving `http://` image links. 
- When transcluded `![image](http://static.pocketcasts.com/...)`, these image links are broken on Obsidian mobile (but they do load on Obsidian desktop!). 
- If I manually change the link to `https://` the image transclusions load properly in Obsidian preview.

**What I tried** 
- I tested with Google Podcasts and Spotify services, and Podcast Note retrieves `https://` links. 
- I didn't test any other of your supported services.

**Requested solution**
- is it possible for you to instruct Podcast Note to retrieve the {{ImageURL}} placeholder as `https://` links.

Vielen Dank!
Tom

**Comment by marcjulianschwarz** [comment]
Guten Abend @DryIce1 ;)

Thank you for pointing out this issue.
Do I understand it correctly that `http` links don't work on the mobile version but they do work with the desktop version?

**Comment by DryIce1** [comment]
Yes, that is my impression about how it works on mobile - the images load if I change them from http to https. 

Also if I change a Spotify import imgURL https to http, it doesn't load.

So it seems important to make them import images as https.

**Comment by marcjulianschwarz** [comment]
Thank you.
Fixed with 1.3.0
