### ISSUE TITLE
A Few Feature Requests

### ISSUE THREAD

**Issue by SamGreenwood1** [marcjulianschwarz/obsidian-podcast-note#19]
- an episode number  placeholder
- a title parcer (to split the title into components like: episode numbers, titles, etc. from what's pulled)

Where do you find the documentation to integrate with the apps?

**Comment by marcjulianschwarz** [comment]
Thank you for the feature request, will add the placeholder to the list in #13.
What do you mean with title parser? For titles you can use the template in the settings.

There is no integration with apps. This plugin works with podcast/episode URLs that you have to copy and paste.
