### ISSUE TITLE
Is it possible to automatically create podcast note for episodes added to Play Next?

### ISSUE THREAD

**Issue by wenlzhang** [marcjulianschwarz/obsidian-podcast-note#2]
It would be great if this can be supported, as one may very likely create notes for those added to the Play Next list in podcast apps. This way, one does not need to manually create notes for each episode.

I found the following resources regarding Pocket APIs, but not sure if it helps:

- [Third party integration](https://support.pocketcasts.com/article/third-party-integration/)
- [New Issue · marcjulianschwarz/obsidian-podcast-note](https://github.com/marcjulianschwarz/obsidian-podcast-note/issues/new)

This feature is similar to what one can do for Readwise and Pocket, e.g. with the following plugins:

- [renehernandez/obsidian-readwise: Sync Readwise highlights into your obsidian vault](https://github.com/renehernandez/obsidian-readwise)
- [nybbles/obsidian-pocket: Pocket integration for Obsidian](https://github.com/nybbles/obsidian-pocket)

**Comment by marcjulianschwarz** [comment]
Sound like a great idea. However I think this would not really fit the podcast note plugin.

The links you shared mention an app called "Tasker" which seems to be an Android app. I don't know how this can help with this issue.

I think getting your play next list into obsidian shouldn't be part of this plugin. But I could try to implement a feature that would let you create a note with a list of URLs. Then this list will be converted into individual podcast notes.

**Comment by wenlzhang** [comment]
> But I could try to implement a feature that would let you create a note with a list of URLs. Then this list will be converted into individual podcast notes.

This would also help improve the workflow of creating podcast notes. Then one may think about how to get a list of URLs from the Play Next list. 😃

**Comment by wenlzhang** [comment]
> But I could try to implement a feature that would let you create a note with a list of URLs.

Would it be possible to make it work for any length of selected mixed text and URLs. The text may be temporary notes/thoughts, and the URLs correspond to podcast episodes. A use case for this would be as follows:

- One takes some notes/thoughts on podcast episodes together with the URLs in Obsidian Mobile.
- One create several podcast notes based on the selected mixed text and URLs.

**Comment by marcjulianschwarz** [comment]
Sounds like a good idea. Will think about this and let you know when I came up with something.

**Comment by marcjulianschwarz** [comment]
Something like this?

https://user-images.githubusercontent.com/67844154/132840604-d8691a38-a6fd-471d-b401-86113286f644.mp4

**Comment by wenlzhang** [comment]
> Something like this?

Yes. This looks great!

**Comment by marcjulianschwarz** [comment]
I just published the new release with this feature.
