### ISSUE TITLE
Sanitize  default placeholders in YAML

### ISSUE THREAD

**Issue by danieltomasz** [marcjulianschwarz/obsidian-podcast-note#20]
Great plugin!

What I could add is to request to sanitize pasted data;
Often it breaks YAML and other plugins like dataview have a problem with it
for example  this podcast https://pca.st/n5f0n138
with placeholder ` title: {{title}}` will give in yaml `title: Placeholder 01: Jurassic Park and the Vampire Project - Taking Control: The ADHD Podcast` which without adding quotes isnt displayed in data view and is breaking yaml syntax
>A colon followed by a space (or newline) ": " is an indicator for a mapping. A space followed by the pound sign " #" starts a comment.
https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

**Comment by marcjulianschwarz** [comment]
Thank you for the feedback.

Yes this makes sense. I think the notes filename is already being sanitized. Will implement this for YAML placeholders too.

**Comment by marcjulianschwarz** [comment]
Has been fixed in version 1.3.2
