### ISSUE TITLE
Add Source

### ISSUE THREAD

**Issue by anoriginalmoniker** [marcjulianschwarz/obsidian-podcast-note#21]
I've been using [Snipd](https://www.snipd.com/) a lot lately. It's allows you access to transcripts of podcasts. I think it's kind of like Airr, but has an Android app.

I would love it if you could add their service as one of the sources on your plugin.

Thanks for your work!

**Comment by marcjulianschwarz** [comment]
Hi @anoriginalmoniker 

Had problems with Snipd (see #10). But I think Snipd has its own podcast plugin for Obsidian.

Could you please provide a link to a Snipd podcast episode, then I will probably be able to add it as a source.

**Comment by anoriginalmoniker** [comment]
I think you're right about Snipd. I couldn't find links to their actual podcast feeds, just to my personal snips. Thanks anyway!
