### ISSUE TITLE
New podcast source: Podcast Addict

### ISSUE THREAD

**Issue by SamejSpenser** [marcjulianschwarz/obsidian-podcast-note#24]
I have exclusively used Podcast Addict as a podcast aggregator for many years now. It will be much simpler and more efficient to use the (excellent) Podcast Note plugin if it recognizes Podcast Addict links, like this: https://podcastaddict.com/episode/131692346.

**Comment by marcjulianschwarz** [comment]
Hi @SamejSpenser,

thank you for the suggestion. Will let you know when a new version with Podcast Addict is available.

**Comment by SamejSpenser** [comment]
> Hi @SamejSpenser,
> 
> thank you for the suggestion. Will let you know when a new version with Podcast Addict is available.

Hi @marcjulianschwarz,

I'm very happy and satisfied with this addition, thank you very much! 😉

**Comment by marcjulianschwarz** [comment]
Hi @SamejSpenser,

the newest commit 40c5d04a92ee2b6b931fa4b1b86cfc69e1f63615 supports Podcast Addict.
You might be able to try it out with the BRAT plugin but I haven't tried it yet.

Version 1.3.2 has been released, supporting Podcast Addict.

**Comment by SamejSpenser** [comment]
> Version 1.3.2 has been released, supporting Podcast Addict.

Hello @marcjulianschwarz,

I just updated Podcast Notes on Obsidian. I tested it, and it worked perfectly fine, exactly as I had in mind.

Again, thank you very much for your prompt availability! 😉
