### ISSUE TITLE
Thank You + Comments about Airr App

### ISSUE THREAD

**Issue by FelipeRearden** [marcjulianschwarz/obsidian-podcast-note#3]
Hello @marcjulianschwarz !!!

First of all, thank you very much for this plug-in! 

This is an amazing plug-in for someone like me who is trying to learn with podcasts. 

I have been trying to create a workflow in Obsidian for my Podcast routine and I'm pretty happy with this plug-in. Thank very much for this :)

I'm a heavy user of Airr App and I wanna share with some thoughts that could make `Podcast Note` The perfect plug-in to work with Airr

## Why Airr is different ?

Airr have two features that makes it different from the other apps:

**1- Highlights of a Podcast Episode (AirrQuotes)**

When listening, the user can "highlight" the conversation (podcast) based on time. For example, the user can highlight the last 45 seconds of the conversation (podcast) 

**2- Transcript**

Airr is able to generate a transcript (text) of a Podcast Episode and of a Highlight Episode (AirrQuote)
- This is extremely useful for someone like me who is not a native English speaker and have to repeat and read to understand 100% of the Podacast :)

Transcript of an Episode 
![76703F57-644B-40AC-8390-0FEA33096E93](https://user-images.githubusercontent.com/85180696/132687926-bf685f99-0b7a-4f53-bd2c-289549feeb40.jpeg)

Transcript of an Highlight
![71D89DC1-C99C-40CE-A1B7-C43632842A29](https://user-images.githubusercontent.com/85180696/132687965-7e4cfc2f-4520-4447-b341-bbe537116596.jpeg)

## Airr URL schema 

To export content from Air, we have two types of url:

### Episode URL

https://www.airr.io/episode/5fc93de3f57679d1dc56ad4e

Contains these elements: 
- Episode Title
- Episode Description 
- Podcast image

This URL is supported by `Podcast Note` plug-in :)

### Highlight URL

https://www.airr.io/quote/601539e0030ce34b1d173a04

Contains these elements:
- Episode Title
- Highlight Description (text defined by the user in the moment of create a highlight)
- Highlight Transcript 

![ABDB4CA6-FC77-4874-88DC-29578E0F4896](https://user-images.githubusercontent.com/85180696/132688907-63d41aa3-c29a-4a4d-83ae-feefa800fb89.jpeg)

This URL is not supported by `Podcast Note` plug-in :(

If you have 10 highlights from an Episode, you would have 10 different URL.

## Airr Export Engine 

For Episode Highlights Airr let the user select more than one URL in a single export 
- In a single exportation, I can have all my URL highlights from a Episode 

![238E3D69-DBAE-4C66-BDDC-B0DEA3F45A8C](https://user-images.githubusercontent.com/85180696/132689003-7005f302-a7a4-4d46-8eb6-5e11a31156d2.jpeg)
![D7D1BC1D-F9A4-483D-BAD3-E1B06E462A4D](https://user-images.githubusercontent.com/85180696/132689023-05029fb1-0322-42af-bd9d-3811baab5dfe.jpeg)

I can use a Apple Shortcuts to create an .md file with all URL in a single document (Note)

What I am trying to say is that we have easy options to deal with this URL before "import" to Obsidian

## Feature Request 

I have been thinking about a workflow with `Podcast Note` and Airr and this is my feature requests:

1- [Support for URL https://www.airr.io/quote/ `Highlight URL`](https://github.com/marcjulianschwarz/obsidian-podcast-note/issues/4)   

2- [Support Multiple URLs in `Podcast Note: Add Podcast Note` - This way I can export all highlights in one command](https://github.com/marcjulianschwarz/obsidian-podcast-note/issues/5)

3- [Airr URL `See More` Is cutting Description](https://github.com/marcjulianschwarz/obsidian-podcast-note/issues/6)

---
Sorry for the long text I hope you like my suggestions :)

Thanks again and have a great day!

**Comment by wenlzhang** [comment]
Thanks for sharing this! This workflow can indeed be very useful for taking podcast notes with Airr.

**Comment by marcjulianschwarz** [comment]
Thank you very much for the feedback and detailed explanation of the Airr app.

I just looked at the source code for an Airr Quote and it seems to be possible to get all of the data you want from there. However when doing an https request, only a simple placeholder is shown instead of the quote/transcript (see image).
You can easily get the description from the meta data but I don't see a way to access the transcript.

If anyone of you knows whether Airr has some sort of API, it would make it a lot easier. 

Additionally, I don't see a way to activate the "see more" button before requesting the webpage.

![Transcript placeholder](https://user-images.githubusercontent.com/67844154/132944158-186721ca-0cbf-4cbe-84b0-88a3cdcb1f76.png)

**Comment by FelipeRearden** [comment]
Update about this issue here: #4 .
