### ISSUE TITLE
[Feature Request] `Airr` Support for AirrQuote URL

### ISSUE THREAD

**Issue by FelipeRearden** [marcjulianschwarz/obsidian-podcast-note#4]
Hello @marcjulianschwarz !!!

Feature Request: Add support for the url Schema https://www.airr.io/quote/601539e0030ce34b1d173a04

If possible create the new placeholders: 

- {{Airr.Quote.Description}}
- {{Airr.Quote.Transcript}}

UsIng the URL as example: https://www.airr.io/quote/601539e0030ce34b1d173a04
![C9C7C5BD-E95E-4B44-8EAA-48665293D57E](https://user-images.githubusercontent.com/85180696/132689792-1f08b497-40d4-4441-aff6-555a11020dc6.jpeg)

- {{Airr.Quote.Description}} >>> Como modificar a voz

- {{Airr.Quote.Transcript}} >>>
...habits of thought and have absorbed so Maney thought patterns and speech patterns from parents and other caretakers and so on that they might kick the **shit out of themselves all day until the very end of the night. And they're like, Wow, I've been a real asshole to myself all day and they're not able to sort of catch the thought trapped in the amber and work with it in the moment. Do you have any advice for those people?**   

**Speaker 2: Well, first of all, it's very normal that everyone has a private voice. Everyone has an inner voice that's speaking to them, some more than others, and sometimes that voice is extremely harsh, difficult challenging. And you, would you say things to yourself. You would never say to any other human being and you would be so embarrassed if it was made public. And then if I would ask you, where does it come from? You'd** say I Well, I said, you know, is there any of that in anyone in your life? And they often say, You know, it's a lot like my father is the way my father used to talk to me. That's why my mother would talk to me. They don't really...

---

Let me know if need more information

Have a great day :)

**Comment by wenlzhang** [comment]
It would be great to be able to extract Airr transcript, if any!

**Comment by marcjulianschwarz** [comment]
As I explained in #3, I don't see a way to extract this information for now. If you find some sort of API for that or know how to get this information with an http request, let me know and I will implement it.

**Comment by wenlzhang** [comment]
Is there any update on supporting Momento and/or Snipd?

**Comment by marcjulianschwarz** [comment]
As I already said, I can't get Snipd to run on my devices.

I was busy with other projects but I will let you know when Momento is supported (I think I can get it done today).

**Comment by FelipeRearden** [comment]
> As I explained in #3, I don't see a way to extract this information for now. If you find some sort of API for that or know how to get this information with an http request, let me know and I will implement it.

Hello @marcjulianschwarz !!!!

First of all, I wanna say I'm sorry for this very late reply. I was trying to find a way to help with this issue. 

I bring some good news. I hope it could help you to implement this :)

### This is What I found 

After a long search and testes I found out that the Obsidian Web Clipper Bookmarlket created by from our communitty friends - link [here](https://forum.obsidian.md/t/obsidian-web-clipper-bookmarklet-with-full-markdown-support-for-images-headings-and-code-blocks/22068) is able to extract information from an AirrQuote link:

Running this URL https://www.airr.io/quote/60153afa030ce32f95173a18 creates this new note in Obsidian

![136789843-4ed80b23-5ae7-42bc-adeb-3524c043c6cf](https://user-images.githubusercontent.com/85180696/136936019-8e608724-4add-440e-b0c3-3028e14f3a80.png)

---

This is the gist for the script: https://gist.github.com/kepano/90c05f162c37cf730abb8ff027987ca3

This is the link from the post in the forum: https://forum.obsidian.md/t/obsidian-web-clipper-bookmarklet-with-full-markdown-support-for-images-headings-and-code-blocks/22068

My hope is that this script could be a source of information for inserting AirrQuotes URL with your plugin.

**Important**: I must say that I have to manually click the `See More` button to get all `AirrQuote Transcript`


---

I hope you could take a look to see if it will help us to full integrate with Airr App 🙏  

Thanks for reading this and I wanna again say I'm sorry for my late reply.

**Comment by marcjulianschwarz** [comment]
Hi!

Thank you for the detailed response. The problem with this is that it is a browser extension, which means it can directly take the html from the browser. My plugin however is using an http request on a given URL which will only return the html visible on page loading.
Thats why I see no way of getting the text behind the `See More` button. Manually clicking the button won't help either since it will only change the html in the browser, reloading the site will immediately undo this.

**Comment by FelipeRearden** [comment]
Hello @marcjulianschwarz !!1

I was afraid of that :( . 

Question: Do you think if the `See More` button was "open" by default  would help us to integrate ?

**Comment by FelipeRearden** [comment]
I'm asking this because we have a last chance of getting this. Airr has a help section that let the users send messages asking for help or FR's. 

I think we have 3 approach to try and I wanna ask for your help to decide:

01- Ask them to get rid of the See More;
02- Ask them to open See More as the default behavior; 
03 - Ask about the API explaining exactly our need and who we are (obsidian community .....). I'm almost sure that they have some kind of API.

I think we should try first `01` and `02` to see what happens.

For `03` I'm gonna need your help to write the text since I am not a developer and not an English native speaker . 

What you think @marcjulianschwarz ?
