### ISSUE TITLE
[Feature Request] Support Multiple URLs in `Podcast Note: Add Podcast Note`

### ISSUE THREAD

**Issue by FelipeRearden** [marcjulianschwarz/obsidian-podcast-note#5]
Hello @marcjulianschwarz !!!

Feature Request: Add the ability to input multiple ULR in the Command `Podcast Note: Add Podcast Note`

For Multiple URLs, the default behavior is `Insert at cursor`
- In my opinion, user will create a Episode Note first then after import highlights (this way, the best option would be to insert the Quotes in the Episode Note)

---
Let me know if you need more information 

Have a great day!

**Comment by marcjulianschwarz** [comment]
You can now create multiple podcast notes using the new `Add Podcast Notes from selection` command. I think this workflow makes more sense. You can have a list with all episodes (maybe even other text or notes in between) and then you just have to select the whole text, run the command and let the plugin create your notes + links.

https://user-images.githubusercontent.com/67844154/132870393-57bfcc3c-0af6-4939-b8f1-8cacd051a52c.mp4

**Comment by marcjulianschwarz** [comment]
Can implement this for AirrQuotes too. But as I said in #3 I can only fetch the description and not the transcript.
