### ISSUE TITLE
[Feature Request] `Airr` URL `See More` Is cutting Description

### ISSUE THREAD

**Issue by FelipeRearden** [marcjulianschwarz/obsidian-podcast-note#6]
Hello again @marcjulianschwarz !!!

`Airr` URL has an text `See More` That collapses Description and cuts a great amount of the text .
![AE793F7A-2305-49CD-9969-70C22422CF0B](https://user-images.githubusercontent.com/85180696/132690432-0e9a8594-f1b3-4241-9906-72abd782aabf.jpeg)

![A62E09CC-7796-4FF4-AEBB-1EB59D0697DC](https://user-images.githubusercontent.com/85180696/132690447-38aee22e-dca4-4631-b391-268dbc67d8a4.jpeg)

Would be amazing if the command `Podcast Note: Add Podcast Note`.  Brings the whole description of the URL.

---
Let me know if you need more information

Have a great day!

**Comment by marcjulianschwarz** [comment]
I wrote about this in issue #3 .
