### ISSUE TITLE
Not handling multiple occurrences of same placeholder

### ISSUE THREAD

**Issue by swehba** [marcjulianschwarz/obsidian-podcast-note#7]
If in the custom template for the plugin (see its config page), you specify the same placeholder — say `{{Title}}` or `{{Date}}` multiple times, the first occurrence of each placeholder is substituted for just fine, but not the subsequent occurrences. 

One other unusually behavior...I have two occurrence of ``{{Date}}`` in my template. The second occurrence doesn't get replaced at all as described above. However, the first occurrence gets replace with the date *and* time instead of just the date. Maybe that's the expected behavior, but I would have expected just the date since that is what the standard Obsidian `{{date}}` placeholder does.

**Comment by marcjulianschwarz** [comment]
Thank your for pointing this out.
Will introduce a new {{Time}} placeholder in the next release and fix the bug with multiple occurrences.

**Comment by marcjulianschwarz** [comment]
The new release has been published. It now contains a placeholder `{{Date}}` and `{{Timestamp}}` which both work as expected.
