### ISSUE TITLE
Custom folder not working

### ISSUE THREAD

**Issue by swehba** [marcjulianschwarz/obsidian-podcast-note#8]
If you configure the plugin to use a custom folder, the podcast episode notes still get inserted at the root of the vault. For example, I have a folder "Podcasts" off the root of my vault where I want these notes to go. However, the continue to go to the root. In fact, what happens is this...let's say the title of the podcast is "blah blah blah". A note gets created at the root of the vault with the title "Podcastsblah blah blah". In other words, the folder path is prefixed as part of the file name.

**Comment by marcjulianschwarz** [comment]
This is a known issue and will be resolved with the next update. For now you can work around this by adding a „/“ after your custom folder name in settings.

**Comment by marcjulianschwarz** [comment]
This has been fixed with the new release.
