### ISSUE TITLE
Feature request: additional fields to extract from the podcast episode

### ISSUE THREAD

**Issue by swehba** [marcjulianschwarz/obsidian-podcast-note#9]
It would be really nice to also extract and have placeholders for the following:

- {{Station}} — the name of the podcast station/show vs. the episode {{Title}}
- {{EpisodeNumber}} — if episodes are numbered for the given station
- {{RunTime}} — the duration of the episode (e.g., 1:23:45)
- {{Tags}} — any tags associated with the episode
- {{AiredDate}} — when the episode aired

I don't know if any of this is possible, but thought I would ask.

**Comment by marcjulianschwarz** [comment]
Moved to #13
